services:
  - type: web
    name: loan-approval-api
    env: python
    plan: free
    region: oregon
    buildCommand: ""
    startCommand: python app.py
    buildCommand: pip install -r requirements.txt
    runtime: python
    pythonVersion: 3.11
